### ISSUE TITLE
Cmake errors

### ISSUE THREAD

**Issue by Jimmy106-e** [geode-sdk/example-mod#11]
Im trying to write another mod but I can't setup VSC because i get these errors from CMake:
`[cmake] CMake Error at CMakeLists.txt:22 (setup_geode_mod):
[cmake]   Unknown CMake command "setup_geode_mod".`
And
`[cmake] -- Found Geode: C:\Users\......\Documents\Geode
[cmake] -- Configuring incomplete, errors occurred!
[cmake] CMake Error at CMakeLists.txt:20 (add_subdirectory):
[cmake]   add_subdirectory given source "C:\Users\panda\Documents\Geode" which is not
[cmake]   an existing directory.`
I already have used VSC for a mod but it's not working today
Any help Appreciated

**Comment by YellowCat98** [comment]
seems like it cant find geode itself, try checking if the GEODE_SDK environment variable exists in your environment variables

**Comment by Jimmy106-e** [comment]
It does and ive checked in CMD and plus cmake finds it but then it says it cant
`{cmake] -- Found Geode: C:\Users\......\Documents\Geode `

**Comment by YellowCat98** [comment]
strange idk why is this happening, is `......` an actual directory or are you just censoring it?

**Comment by Jimmy106-e** [comment]
censoring

**Comment by sweetberryjuicee** [comment]
did you run geode sdk install? if you did can you verify if its in your path by running echo %GEODE_SDK%

**Comment by Jimmy106-e** [comment]
> did you run geode sdk install? if you did can you verify if its in your path by running echo %GEODE_SDK%

yes and `echo %GEODE_SDK% does print the path

**Comment by sweetberryjuicee** [comment]
which way you installed it? it seems like you installed it to the documents

**Comment by sweetberryjuicee** [comment]
manually installing is not recommended

**Comment by Jimmy106-e** [comment]
I used winget

**Comment by YellowCat98** [comment]
> I used winget

i think theyre talking about the sdk, not the cli

**Comment by YellowCat98** [comment]
either way winget isnt recommended as its outdated for installing the cli

**Comment by sweetberryjuicee** [comment]
ye

**Comment by Jimmy106-e** [comment]
I also updated it manually

**Comment by sweetberryjuicee** [comment]
winget upgrade GeodeSDK.GeodeCLI?

**Comment by Jimmy106-e** [comment]
Its on v3.0.5

**Comment by Jimmy106-e** [comment]
could it be my binaries?

**Comment by Jimmy106-e** [comment]
> could it be my binaries?

cause i get this when i try to update them: `| Fail | Downloading binaries failed: error decoding response body`

**Comment by YellowCat98** [comment]
you need the binaries but the error still shouldnt happen

**Comment by YellowCat98** [comment]
you can just download the binaries manually tho shouldnt cause any issues

**Comment by Jimmy106-e** [comment]
where do i put them

**Comment by sweetberryjuicee** [comment]
i think reinstalling may work but use scoop this time

**Comment by YellowCat98** [comment]
download the binaries through github https://github.com/geode-sdk/geode/releases/tag/v3.1.1 dont get the installer, get the files and go to your geode directory, create a bin folder with a folder named "3.1.1" folder in it, and then place the binaries there

**Comment by sweetberryjuicee** [comment]
arent they trying to build? i think its related to the way they installed the cli

**Comment by YellowCat98** [comment]
i think theyre building through vscode

**Comment by Jimmy106-e** [comment]
> arent they trying to build? i think its related to the way they installed the cli

i am missing the binaries

**Comment by sweetberryjuicee** [comment]
then run geode sdk install-binaries

**Comment by YellowCat98** [comment]
they said that it gives them an error

**Comment by Jimmy106-e** [comment]
Ok Updated

**Comment by sweetberryjuicee** [comment]
yippie finally

**Comment by Jimmy106-e** [comment]
Still same errors 😔

**Comment by sweetberryjuicee** [comment]
response body?

**Comment by Jimmy106-e** [comment]
> Im trying to write another mod but I can't setup VSC because i get these errors from CMake: `[cmake] CMake Error at CMakeLists.txt:22 (setup_geode_mod): [cmake] Unknown CMake command "setup_geode_mod".` And `[cmake] -- Found Geode: C:\Users\......\Documents\Geode [cmake] -- Configuring incomplete, errors occurred! [cmake] CMake Error at CMakeLists.txt:20 (add_subdirectory): [cmake] add_subdirectory given source "C:\Users\panda\Documents\Geode" which is not [cmake] an existing directory.` I already have used VSC for a mod but it's not working today Any help Appreciated

this

**Comment by Jimmy106-e** [comment]
same response from cmake in vscode

**Comment by sweetberryjuicee** [comment]
are you sure you followed the tutorial correctly? this musnt happen at all

**Comment by Jimmy106-e** [comment]
yup

**Comment by Jimmy106-e** [comment]
should i just fully uninstall and reinstall geode-sdk?

**Comment by sweetberryjuicee** [comment]
yeah but install it with scoop this time

**Comment by Jimmy106-e** [comment]
ok, but how do I uninstall it?

**Comment by sweetberryjuicee** [comment]
idk maybe run geode sdk uninstall i never used it before tbh

**Comment by Jimmy106-e** [comment]
great
`scoop install geode-sdk-cli
Couldn't find manifest for 'geode-sdk-cli'.`

**Comment by Jimmy106-e** [comment]
> idk maybe run geode sdk uninstall i never used it before tbh

please help?

**Comment by sweetberryjuicee** [comment]
run scoop bucket add extras

**Comment by Jimmy106-e** [comment]
i just did

**Comment by sweetberryjuicee** [comment]
the manifest is in extras so

**Comment by sweetberryjuicee** [comment]
ok then run scoop install geode-sdk-cli

**Comment by Jimmy106-e** [comment]
> `scoop install geode-sdk-cli Couldn't find manifest for 'geode-sdk-cli'.`

what i did here but i got the manifest error

**Comment by Jimmy106-e** [comment]
Fully installed again but the same cmake errors
`[cmake] -- Found Geode: C:\Users\panda\Documents\Geode
[cmake] -- Configuring incomplete, errors occurred!
[cmake] CMake Error at CMakeLists.txt:20 (add_subdirectory):
[cmake]   add_subdirectory given source "C:\Users\panda\Documents\Geode" which is not
[cmake]   an existing directory.
[cmake] 
[cmake] 
[cmake] CMake Error at CMakeLists.txt:22 (setup_geode_mod):
[cmake]   Unknown CMake command "setup_geode_mod".
[cmake] 
[cmake] `
